### ISSUE TITLE
error file not found

### ISSUE THREAD

**Issue by Polarwing** [BrianLYS/MediumTopics#1]
hello I found the error when I run the PDF path, but I petty sure that my PDF folder is located correctly, Thanks in advance :)

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[32], line 17
     14         loaders.append(loader)
     15     return loaders
---> 17 loaders = create_pdf_loaders(pdf_folder_name)
     18 print(loaders)

**Comment by BrianLYS** [comment]
Hello @Polarwing , sorry for the wait ! Went on a holiday haha. Lemme know if it works for you now, I can get it to work on colab now.

<img width="781" alt="image" src="https://github.com/BrianLYS/MediumTopics/assets/83122861/5469d0bf-3a05-48c1-8b82-c4a85314dca1">

Seems the packages get updated pretty often so in case new versions come out and it breaks again, for future issues you can just run `!pip install -r requirements.txt` which has fixed versions. (You'd need to place the requirements.txt in the colab or wherever the code is being ran from.)
